    redis:
        image: redis
        env_file:
          - .env
        command: redis-server --requirepass ${REDIS_PASSWORD}
        ports:
          - 6379:6379
        volumes:
          - ./redis-db:/data