    kafka:
        image: apache/kafka
        container_name: kafka
        hostname: kafka
        user: root 
        ports:
          - "9092:9092"
          - "29092:29092"
          - "9093:9093"
        volumes:
          - ./kafka_data:/tmp/kafka-logs
        environment:
          # KRaft Settings
          KAFKA_PROCESS_ROLES: 'broker,controller'
          KAFKA_NODE_ID: 1
          KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      
        # Listener Settings
          KAFKA_LISTENERS: 'INTERNAL://:29092,EXTERNAL://:9092,CONTROLLER://:9093'
          KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://kafka:29092,EXTERNAL://localhost:9092'
          KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
          KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT'

          # General Settings
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
          KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
          KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
          KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
